version: 1.0
dataset_cfg:
  dataset_name: CARRADA
  warehouse: /home/liyuqin/datasets/
  carrada: /home/liyuqin/datasets/Carrada/
  weight_path: /home/liyuqin/projects/record//configs/carrada/weights_config
  project_path: /home/liyuqin/projects/record//
  annot_type: dense
model_cfg:
  name: MV-RECORD-OI
  process_signal: true
  w_size: 256
  h_size: 256
  nb_classes: 4
  in_channels: 1
  win_size: 10
  backbone_pth: /home/liyuqin/projects/record//models/configs/mv_record.yaml
  width_mult: 1.0
  norm: layer
train_cfg:
  ckpt_dir: logs/carrada
  n_epoch: 500
  batch_size: 4
  accumulate_grad: 2
  lr: 0.0003
  lr_step: 20
  loss_step: 100
  val_step: 2000
  viz_step: 4000
  loss: wce_w10sdice
  transformations: hflip, vflip
  norm_type: tvt
  shuffle: true
