version: 1.0
dataset_cfg:
  dataset_name: ROD2021
  docker: false
  base_root: /home/liyuqin/datasets/CRUW/
  data_root: /home/liyuqin/datasets/CRUW/sequences
  anno_root: /home/liyuqin/datasets/CRUW/annotations
  data_dir: /home/liyuqin/projects/record/prepared_data/
  anno_ext: .txt
  train:
    subdir: train
    seqs:
    - 2019_04_09_BMS1000
    - 2019_04_09_PMS1001
    - 2019_04_30_MLMS002
    - 2019_04_30_PM2S003
    - 2019_05_09_MLMS003
    - 2019_05_23_PM1S013
    - 2019_05_29_BCMS000
    - 2019_05_29_PCMS005
    - 2019_09_29_ONRD002
    - 2019_04_09_BMS1001
    - 2019_04_09_PMS2000
    - 2019_04_30_PBMS002
    - 2019_04_30_PM2S004
    - 2019_05_09_PBMS004
    - 2019_05_23_PM1S014
    - 2019_05_29_BM1S016
    - 2019_05_29_PM2S015
    - 2019_09_29_ONRD006
    - 2019_04_09_BMS1002
    - 2019_04_09_PMS3000
    - 2019_04_30_PBMS003
    - 2019_05_09_BM1S008
    - 2019_05_09_PCMS002
    - 2019_05_23_PM1S015
    - 2019_05_29_BM1S017
    - 2019_05_29_PM3S000
    - 2019_09_29_ONRD011
    - 2019_04_09_CMS1002
    - 2019_04_30_MLMS000
    - 2019_04_30_PCMS001
    - 2019_05_09_CM1S004
    - 2019_05_23_PM1S012
    - 2019_05_23_PM2S011
    - 2019_05_29_PBMS007
    - 2019_09_29_ONRD001
    - 2019_09_29_ONRD013
  valid:
    subdir: train
    seqs:
    - 2019_04_09_PMS1000
    - 2019_04_30_MLMS001
    - 2019_05_29_MLMS006
    - 2019_09_29_ONRD005
  test:
    subdir: test
  demo:
    subdir: demo
  mean_cplx:
  - -3.19201617e-06
  - -1.05546117e-05
  std_cplx:
  - 0.06594299
  - 0.06600033
  mean_ampl: 0.04367220899658192
  std_ampl: 0.08244549426031758
model_cfg:
  name: RECORD
  backbone_pth: /home/liyuqin/projects/record//models/configs/record_cruw.yaml
  width_mult: 1.0
  sensor_config: sensor_config_rod2021
  in_channels: 8
  n_chirps: 4
  nb_classes: 3
  norm: layer
  max_dets: 20
  peak_thres: 0.3
  ols_thres: 0.3
  # CBAM Attention Module Configuration
  use_cbam: true                # Enable/disable CBAM attention
  cbam_reduction: 32            # Channel reduction ratio for CBAM 可调整：8, 16, 32
  cbam_kernel_size: 1           # Kernel size for spatial attention (3 or 7) 可选：3 或 7
#  # 方案1：轻量级 CBAM
#  use_cbam: true
#  cbam_reduction: 32      # 更大的压缩比，参数更少
#  cbam_kernel_size: 3     # 更小的卷积核
#  # 方案2：标准 CBAM
#  use_cbam: true
#  cbam_reduction: 16
#  cbam_kernel_size: 7
#  # 方案3：强注意力 CBAM
#  use_cbam: true
#  cbam_reduction: 8       # 更小的压缩比，注意力更精细
#  cbam_kernel_size: 7
confmap_cfg:
  confmap_sigmas:
    pedestrian: 15
    cyclist: 20
    car: 30
  confmap_sigmas_interval:
    pedestrian:
    - 5
    - 15
    cyclist:
    - 8
    - 20
    car:
    - 10
    - 30
  confmap_length:
    pedestrian: 1
    cyclist: 2
    car: 3
train_cfg:
  ckpt_dir: logs/rod2021_cbam_light
  n_epoch: 100
  batch_size: 10
  accumulate_grad: 1
  lr: 0.001
  optimizer: adam
  scheduler: exp
  loss: bce
  alpha_loss: 0.5
  win_size: 12
  train_step: 1
  train_stride: 4
  use_ampl: false
  normalize: false
  train_log_step: 1000
  val_log_step: 100
  test_log_step: 200
  aug:
    mirror: 0.5
    reverse: 0.5
    gaussian: 0.0
test_cfg:
  test_step: 1
  test_stride: 1
  rr_min: 1.0
  rr_max: 20.0
  ra_min: -60.0
  ra_max: 60.0
